[package]
name = "rust-webServer"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = {version = "2.2.4", features = ["chrono"]}
diesel-async = { version = "0.5.1", features = ["postgres"] }
chrono = "0.4"
